apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base
  - volumes/

resources:
  - namespace.yaml
  - mariadb-secrets-sealed.yaml
  - shibboleth-secrets-sealed.yaml
  - loadbalancer.yaml

namespace: prod
