apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb
  namespace: prod
spec:
  encryptedData:
    root_password: AgBe5faxssmVGvafEa1mZbxfgsMeN4x/t687uEpFCHp/OD++6VDl7iU1Bhj+Qz4ZSDLVqllLzsaIp/dE9JHLoFfElbvF2f7xo0guiKvK45o4t7WicmhI0l0fgNTBZ/nndk5Ln2EOU6oQT9oGcSKIxk7yiBlhaJdwSb3eGL082RPu4VmYM48XKewFixrz4xUOk3WDc6WVk96rJd1XXgcYbUycCPab3eg1tyCh+EjGYOD01tQQey9ZMw+r/1a5kWl+Aa1XQEixisG4CMlkkRvGoma+0inuFbrLs7mLBkkvQe1YYHGtNWt+ZF00uaUwWDcRd8Og4KO12JG2AoEmLm5bj+R8FFlYMHHP8Nzhs4MV0lZscABb5hkY0myDKYlJxacJbQwSCEfhNCXJMmTSqwRgExSwWm4AHaemeMGFzP76ZqP9xJQKxM5RIQMPz0sddfC44cy7lz5SxsQQxkt+flCcQoULkUfCEs0PiIkr1o6G6kxxiX6ZPEm2UCLFVO2UEYJpS1em6tCajXSIDDA/ZO8XhUQ+pzagsQEc1Hro1EOoQuLrqcdtwiLbNIJSXo6SfXHz/yLfXsBbNrO6XJ2V8aHyFqBZN/N0/1+HMc/l2tJlDnkbDaIl35jN00b8ALFqg0aLSNhKInZbBwLs0vT2+Q8qjhMsnUkm/d9ZTx6RQxL14WRc3sxIxUPIMX916oU0TB3xALmrjPCcNpqjwpyPP2udAZ0AU2gn5g==
    user_password: AgDL3r8FxEdXMUQgtlWOgsvEQ7YXI1ny8fk7ArSG2x+AA3wq9glxLyTuj3Y4+bF955DkQ3/0cOnjXsatRh1LEfzO92fLHx32w3CntGBjiqGcvbC8n3WTt4zg1LPanAM0UgWoxGHmhaFyOboIEQ6Tz8kTHCnHMXMpLFXRCUCsI3vcKIQ+P0FisuQTemF7dgIakoKwtfTZNZlLx6DbBQXllocuJ00kWdZWcfsbRw70eUix7Ow9WNm1rBvDcMIA6n28xQFP9i0SrACf+3BuRNlClrzjxJH5Mb/VbrLpHDH9cSQMkaW/HNtrRMJcgj9EpPb5dKvEhibVHSUKmrQcpcdHWh07S3LSI3b4LbQ0Px+Q0IVl/k4o0u7lDPRTWnO9FQ2VvKzIRHOyv1XX9Y67hEqq6145BPfOUj0GsBuIVqP/f0K/QwI0J+OIAWOqKFfG+C5rhMKbC+3xAa0kN+imSoE6S6kMlTnqamRYQid4DtQrLSu8tVRVnBnJGv7iwF5er+O8vEP54qL+fQVRT8CUXNIJ1w7a7FWJfmWV7i1ZlSxsNeZLt7d+LNRQyoY/kfhc+MPe+R/n2jJlvJXEYJemvgBY9MSWl6GI6+d+zl5pkgbfWWgRJHNwZYgf6CLJEl4QtTni8Ajr86aif60fAUrzRBSZFyUGb8caNiiQiHRPJr9fY56v/r3VQUJB8i8JLl2Ehp88zTSj+WKEpxnNnkk7525N6MrDYVlA3S62qKAd
  template:
    metadata:
      name: mariadb
      namespace: prod

