apiVersion: v1
kind: Service
metadata:
  name: nomination-service
spec:
  ports:
    - name: uwsgi
      protocol: TCP
      targetPort: 5000
      port: 5000
  selector:
    role: flask-application-service
