apiVersion: v1
kind: Service
metadata:
  name: http-test-svc
  labels:
    app: fossFund-nomination
    role: http-test-svc
spec:
  selector:
    role: http-test
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 8090
  type: NodePort
