apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    role: database-service
    app: fossfund-nomination
spec:
  selector:
    role: database
  ports:
    - name: mariadb
      protocol: TCP
      targetPort: 3306
      port: 3306
